### ISSUE TITLE
Nie da się zalogować. Nazwa użytkownika niepoprawna

### ISSUE THREAD

**Issue by Mister5Master** [JakubekWeg/Mobishit#1]
Jak już wyżej wspomniałem, podałem dane do mobirega i nie chce się zalogować, twierdząc, że wpisałem złą nazwę użytkownika.

**Comment by maro159** [comment]
U mnie było to samo, ale już działa 👍

**Comment by Mister5Master** [comment]
Sprawdzałem drugi raz, nie działa dalej.

**Comment by Igorexus** [comment]
U mnie również nie działa.

**Comment by borstrze** [comment]
U mnie też nie działa

**Comment by JakubekWeg** [comment]
Pracuje nad tym, jednak nie mam pojęcia dlaczego występuje ten błąd, osobiście sam go nie mam.

**Comment by Igorexus** [comment]
Przetestuj na wirtualnej maszynie z androidem?

**Comment by JakubekWeg** [comment]
Testuje na 4 emulatorach z Androidami 4.0, 4.4, M, O oraz P i nie mam najmniejszego problemu :\ Ludzie u mnie w klasie też nie mają problemu. Pamiętajcie, że login musi kończyć się hostem (.zsl-krakow)

**Comment by JakubekWeg** [comment]
Problem rozwiązany wraz z wersją 1.0.1 proszę o aktualizację. Dziękuję za zgłaszanie błędu.
