### ISSUE TITLE
More fine grained notification settings 

### ISSUE THREAD

**Issue by jakub-gonet** [JakubekWeg/Mobishit#11]
Would be nice if notifs could be enabled for some subjects or only for marks which app updated automatically (so no notifs for manual register update)

**Comment by JakubekWeg** [comment]
Ok, i will add an option in preferences for that. However we are working on the update 1.2 which introduces new notifications system - (Almost) Instant notifications, so we need some time to implement new stuff. 
Please be patient.

BTW, thanks for supporting us and adding new issues.

**Comment by jakub-gonet** [comment]
Sure, that will do.

Nice to hear that, I can also help with RE of mobireg if needed (mostly website, as you propably already decompiled app) - just PM me on FB or ping me here ;>

**Comment by JakubekWeg** [comment]
done
