### ISSUE TITLE
Poprawa oceny

### ISSUE THREAD

**Issue by krawczyk99** [JakubekWeg/Mobishit#2]
W moim przypadku 1 poprawione na 6 jest wpisane do mobiregu jako [1 | 4] (czyli liczona jest tylko ocena 4)
Mobishit traktuje to jako dwie osobne oceny - 1 i 4, przez co źle liczy średnią.

**Comment by JakubekWeg** [comment]
Masz wersję 1.1?

**Comment by krawczyk99** [comment]
Tak

**Comment by JakubekWeg** [comment]
Ech, jedna linijka. Proszę spróbuj aktualnie udostępnionej wersji i daj znać czy działa poprawnie.
[Pobierz APK](https://github.com/JakubekWeg/Mobishit/blob/master/app/release/mobishit.apk?raw=true)
