### ISSUE TITLE
Add option for scheduling exams 

### ISSUE THREAD

**Issue by jakub-gonet** [JakubekWeg/Mobishit#7]
This could be integrated from web version of mobireg or just list of exams added manually with settable notifications.

**Comment by JakubekWeg** [comment]
In version 1.2 there will be "Sprawdziany" fragment well as "Porównania" (it uses both "Porówniania" i "Rankingi" from web version). It looks like this:
![inkedscreenshot_20181111-223047_li](https://user-images.githubusercontent.com/20194971/48318479-6b066a00-e5f9-11e8-9022-6c267ab9afcd.jpg)
To provide best user experience the feature uses special, dedicated server which handles this quite heavy process (login in, going through menu, processing HTML code and getting important data by regexes) for you. The app only shows it in nice way.

Adding manually exams is more difficult to do. I'm going to add integration with Android system calendar, so you can see events in Mobishit as well as in Calendar app and share one calendar with other people (we do that in my class, we add an event and everybody sees it). However It's not very priority feature, so It's not going to be implemented in next release(s).

As always, let me know what do you think about it, would you like something to be changed/added?

**Comment by jakub-gonet** [comment]
Looks good ;>
